### ISSUE TITLE
Open the code of SwinIR + LDL

### ISSUE THREAD

**Issue by gaowq2017** [csjliang/LDL#4]
Hi, thanks for sharing the code. Can you sharing the train and test code of SwinIR + LDL. Thanks

**Comment by csjliang** [comment]
Hi,

Thanks for your attention to our work. For testing, we have released the pre-trained model of SwinIR+LDL. You can simply uncomment&comment the corresponding lines of `network_g `and `pretrained_network_g` in the `test_LDL_xx_x4.yml` file for the inference of SwinIR+LDL. For training, it is also easy to implement. You need also modify the corresponding lines of `network_g `and `pretrained_network_g` in the `train_LDL_xx_x4.yml` file. The pre-trained network that is used for initialization can be found in the official repository of SwinIR.

**Comment by gaowq2017** [comment]
Hi,
Thanks for your advises. I am success to testing the code. But Loading the SwinIr pretrained model that have missmatch issue, the set of .yml file as follow:
![image](https://user-images.githubusercontent.com/29697367/163515383-1c63d4a1-8958-48aa-8079-2fe19ed7bc85.png)
![image](https://user-images.githubusercontent.com/29697367/163515407-ca39d967-1094-47a9-8209-4833afe7002b.png)
The result as follow:
![image](https://user-images.githubusercontent.com/29697367/163515455-c145ba1b-1f26-4009-bda5-79cebadc8f33.png)

**Comment by csjliang** [comment]
Please use the `test_LDL_Synthetic_x2.yml` file, comment the `network_g `and `pretrain_network_g `for RRDB, and uncomment the `network_g `and `pretrain_network_g `for SwinIR. Thanks.
