### ISSUE TITLE
The pretrain model of scale=2

### ISSUE THREAD

**Issue by gaowq2017** [csjliang/LDL#5]
Hi, i download the pretrain model file that are scale=4. Can you sharring the scale=2 pretrain model file? The parameter scale=4 isn't change in class RRDBNet as follow:
![image](https://user-images.githubusercontent.com/29697367/162357846-b9968ba3-274b-48f3-83bc-63e547c53213.png)

**Comment by csjliang** [comment]
Hi,

Thanks for your suggestion. We have released the pre-trained models and the datasets for the experiments of scale=2. 

The scale and other parameters of the class are specified in the yml file for easy modification, not in the definition of the class.

**Comment by gaowq2017** [comment]
> Hi,
> Thanks for your suggestion. We have released the pre-trained models and the datasets for the experiments of scale=2.
> The scale and other parameters of the class are specified in the yml file for easy modification, not in the definition of the class.
Hi,
Thanks i known it. Whether the model is uploaded to Google Drive or Baidudisk? I directly use existed file have issues as follow:
![image](https://user-images.githubusercontent.com/29697367/162863928-4188eff9-953a-4ae0-a6a4-410403e4dfa7.png)

**Comment by csjliang** [comment]
The pre-trained models are hosted on GoogleDrive via the same link. Please update your local project and use the yml file of scale=2 we have provided, and follow the instructions for testing. Thanks.
