### ISSUE TITLE
inference error 

### ISSUE THREAD

**Issue by zhangyunming** [csjliang/LDL#6]
hi 

when i test  swinir in  /inference/inference.py (two others are ok)

from basicsr.archs.rrdbnet_arch import RRDBNet
from basicsr.archs.srresnet_arch import MSRResNet
from basicsr.archs.swinir_arch import SwinIR

#set up model
#model = RRDBNet(num_in_ch=3, num_out_ch=3, num_feat=64, num_block=23, num_grow_ch=32)
#model = MSRResNet(num_in_ch=3, num_out_ch=3, num_feat=64, num_block=16, upscale=4)
 model = SwinIR(upscale=4, img_size=(64, 64),
               window_size=8, img_range=1., depths=[6, 6, 6, 6],
                embed_dim=180, num_heads=[6, 6, 6, 6], mlp_ratio=2, upsampler='pixelshuffle')

#model.load_state_dict(torch.load(args.model_path)['params'], strict=True)
 model.load_state_dict(torch.load(args.model_path), strict=True)

ir occured error ,  whats the SwinIR params

thanks

**Comment by csjliang** [comment]
Hi, Thanks for your attention to our work. In your setting, the parameters (e.g., depth, num_heads) of the SwinIR model are mismatched to our released model. Please set the parameters by referring to the yml file we provided, or follow our instructions to test by using `test.py`.
