### ISSUE TITLE
the difference of type A, B and C

### ISSUE THREAD

**Issue by jiamingNo1** [csjliang/LDL#7]
Hi, in figure 5, the sigma values for type A, B, and C patches are 0.25, 0.39, 0.67. These numbers are setted originally or calculated by the input image patch?

**Comment by csjliang** [comment]
Hi, thanks for your attention to our paper. The sigma values in figure 5 are calculated by eq. (4) by using the respective patch in the figure. Thanks.

**Comment by jiamingNo1** [comment]
Thanks!
